# Generated by Django 4.2 on 2025-04-07 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hexapawn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='from_pos',
        ),
        migrations.RemoveField(
            model_name='move',
            name='to_pos',
        ),
        migrations.AddField(
            model_name='move',
            name='from_col',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='move',
            name='from_row',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='move',
            name='to_col',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='move',
            name='to_row',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='move',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hexapawn.game'),
        ),
    ]
